name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore src
      - name: Build
        run: dotnet build ./src
      - name: Unit Test
        run: dotnet test  --no-build ./src
  Release:
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore src
      - name: Publish Release
        run: |
          dotnet publish ./src -o ./dist
          cd ./dist && zip -r function.zip . && cd ..
          ls ./dist

    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
